version: '3'
services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pwd
    volumes:
      - ./:/root/.pgadmin
    ports:
      - "5050:80"

